server:
  port: 8080
 
spring:
  application:
    name: spring-cloud-zuul
  cloud:
    consul:
      discovery:
        hostname: 10.4.1.216
        service-name: ${spring.application.name}
        register: true
      host: 10.2.6.47
      port: 8500
 
zuul:
  routes:
    service-producer:
      path: /hello/**
      serviceId: service-producer